# Generated by Django 5.0.1 on 2024-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
